config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :students, param: :unique_hash do
    resources :exercises
    get "students/new", to: "studenst#new"
    get "students/:unique_hash/exercises/:id", to: "exercises#show"
  end
  post "students/new"

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :student
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :exercises, dependent: :destroy
  validates :email_address,
    format: { with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/,
              message: "Email address not valid." },
    allow_blank: false,
    uniqueness: true

  def unique_hash
    Student.hashids.encode(id)
  end

  def self.id_from_unique_hash(hash)
    Student.hashids.decode(hash)[0]
  end

  def self.find_by_unique_hash(hash:, exercise_id: nil)
    query = Student.includes(:exercises)
    query = query.where(exercises: { id: exercise_id }) if exercise_id
    query.find(Student.id_from_unique_hash(hash))
  end

  private
    def self.hashids
      @hashIds ||= Hashids.new("7YTg1aYAmIL8FU_uaEMTAw", 10)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  def index
    @student = Student.find_by_unique_hash(hash: params[:student_unique_hash])
    redirect_to(student_exercise_path(@student.unique_hash,
                                      @student.exercises.first))
  end

  def show
    @student = Student.find_by_unique_hash(hash: params[:student_unique_hash],
                                          exercise_id: params[:id])
    @exercise = @student.exercises.first
    if @exercise.state == "INITIAL"
      @exercise.exercise_begin = DateTime.now.new_offset(0)
      @exercise.state = "IN_PROGRESS"
      @exercise.save
    elsif @exercise.state == "COMPLETED"
      render "done"
    end
    @exercise_snippet = {}
    @exercise_snippet["Ruby"] =
      { text: File.open('app/views/exercises/snippets/exercise.rb').read,
        aceMode: "ace/mode/ruby" }
    @exercise_snippet["Java"] =
      { text: File.open('app/views/exercises/snippets/exercise.java').read,
        aceMode: "ace/mode/java" }
  end

  def update
    @student = Student.find_by_unique_hash(hash: params[:student_unique_hash],
                                          exercise_id: params[:id])
    @exercise = @student.exercises.first
    @exercise.exercise_end = DateTime.now.new_offset(0)
    @exercise.state = "COMPLETED"
    puts params
    @exercise.exercise_response = params[:exercise][:exercise_response]
    @exercise.language = params[:exercise][:language]
    @exercise.save
    render "done"
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
    if new_student_params
      create
    else
      render "new"
    end
  end

  def create
    @student = Student.new(new_student_params)
    if @student.save
      @exercise = @student.exercises.create(state: 'INITIAL')
      redirect_to(student_path(@student.unique_hash))
    else
      render "new"
    end
  end

  def show
    @student = Student.find_by_unique_hash(hash: params[:unique_hash])
  end

  private
    def new_student_params
      if params[:student].nil? || params[:student].empty?
        return false
      else
        return params.require(:student).permit(:name, :email_address)
      end
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/exercises/_intro.html.erb
Hi, <%= @student.name %>. We have a problem. Rupert the Robot is being held
captive by the evil Dr. Tamale. He's locked up in a room, and the only way he
can get out is if, for any given n, he can calculate the nth Fibonacci number
in the famous
<a href="https://en.wikipedia.org/wiki/Fibonacci_number">Fibonacci series</a>.
</br>
Here's where we need your help. Rupert has an internal terminal where he
can run any source code that you provide him, but he doesn't know beans about
software. Your task is to write a function that will calculate the nth
Fibonacci number. The function signature, and a few examples, have been 
provided for you. Good luck!

app/views/exercises/done.html.erb
<div class="center-block col-xs-8" style="float:none">
  ID: <%= @exercise.id %></br>
  student: <%= @exercise.student_id %></br>
  State: <%= @exercise.state %></br>
  Begin: <%= @exercise.exercise_begin %></br>
  End: <%= @exercise.exercise_end %></br>
  language: <%= @exercise.language %></br>
  response: <%= @exercise.exercise_response %></br>
</div>

app/views/exercises/show.html.erb
<style type="text/css" media="screen">
  #editor {
    height: 500px;
    position: relative;
  }
</style>

<div class="center-block col-xs-8" style="float:none">
  <%= render("exercises/intro.html.erb")%>

  <%= form_for :exercise,
    method: :put,
    html: { onsubmit: 'putResponseInForm()' } do |f| %>

    <%= f.hidden_field :id %>
    <%= f.text_area :exercise_response, class: "hidden", id: "exercise_response" %>

    Language: <%= f.select :language,
          options_for_select(@exercise_snippet.keys),
          {},
          onchange: 'updateTemplate(this)' %>
    <div id="editor">
    </div>
    <%= f.submit 'Submit' %>
  <% end %>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="/ace-builds/src-noconflict/ace.js" type="text/javascript" charset="utf-8"></script>
<script>
  var editor = ace.edit("editor");
  editor.setTheme("ace/theme/chrome");
  editor.getSession().setMode("ace/mode/java");
  editor.$blockScrolling = Infinity

  var changedSnippet = false;
  editor.getSession().on('change', function() {
    changedSnippet = true;
  });

  function putResponseInForm() {
    document.getElementById("exercise_response").value = editor.getValue();
  }

  function updateTemplateWithKey(key) {
    var exercise_snippets = <%= raw(@exercise_snippet.to_json) %>
    var curr_snippet = exercise_snippets[key];
    editor.getSession().setMode(curr_snippet["aceMode"]);
    if (changedSnippet) {
      var overwrite = confirm("Overwrite text with new starter template?");
      if (!overwrite) {
        return;
      }
    }
    editor.setValue(curr_snippet["text"]);
    changedSnippet = false;
    editor.clearSelection()
  }

  function updateTemplate(select) {
    updateTemplateWithKey(select.value);
  }

  $(function initTemplate() {
    updateTemplateWithKey("<%= @exercise_snippet.keys.first %>");
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodingChallenge</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag("https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css") %>
  <%= javascript_include_tag("https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js") %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/new.html.erb
<style>
  .field_error {
    color: red;
  }
</style>
<div class="center-block col-xs-4" style="float:none">
  <div class="text-center">
    <h1>Join the Challenge!</h1>
  </div>
  <%= form_for :student, url: {action: :new} do |f| %>
    <div class="form-group">
      <%= f.label :name, "Name:" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :email_address, "Email Address:" %>
      <%= f.text_field :email_address, class: "form-control" %>
      <% if @student %>
        <div class="field_error">
          <%= @student.errors.messages[:email_address][0] %>
        </div>
      <% end %>
    </div>

    <%= f.submit 'Sign up' %>
  <% end %>
</div>

app/views/students/show.html.erb
<div class="center-block col-xs-8" style="float:none">
  <div>
    Welcome, <%= @student.name %> to the Backstop coding challenge!
  </div>

  On the next screen, you will be presented with a coding challenge. A timer will
  start as soon as you navigate to the next page, and it will stop when you
  submit your solution. The person who submits a correct solution in the least
  amount of time will be declared the winner of the competition and will be
  awarded the grand prize! It should take you no more than 30 minutes to 
  complete the challenge, so when you're ready, go ahead and click that 
  button, and start coding. Good luck!

  <div class="right-block">
  <%= button_to("I'm ready!", student_exercises_path(@student.unique_hash),
               method: 'get') %>
   <div>
</div>

app/views/students/update.html.erb
<h1>Done, <%= @student.name %></h1>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>